language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ee-module' ]; then cd .. && eval "mv $currentfolder generator-ee-module" && cd generator-ee-module; fi

